/** TypeBox validators generated by bun run forms:sync; no runtime compiler. */
import type { Static } from '@sinclair/typebox';
import type { PropertyConditionSchema } from '@core/module-engine-schema';
import type { FormTransportSchema, FormControlBehaviorSchema, FormChallengeResponseSchema, FormJsonResponseSchema, TurnstileConfigurationSchema, TurnstileApiSchema, FormValidationResponseSchema, FormSuccessResponseSchema, FormResponseContractSchema } from '@core/forms-schema';
export function checkCondition(value: unknown): value is Static<typeof PropertyConditionSchema>;
export function checkTransport(value: unknown): value is Static<typeof FormTransportSchema>;
export function checkControl(value: unknown): value is Static<typeof FormControlBehaviorSchema>;
export function checkChallenge(value: unknown): value is Static<typeof FormChallengeResponseSchema>;
export function checkJsonResponse(value: unknown): value is Static<typeof FormJsonResponseSchema>;
export function checkTurnstileConfiguration(value: unknown): value is Static<typeof TurnstileConfigurationSchema>;
export function checkTurnstileApi(value: unknown): value is Static<typeof TurnstileApiSchema>;
export function checkValidationResponse(value: unknown): value is Static<typeof FormValidationResponseSchema>;
export function checkSuccessResponse(value: unknown): value is Static<typeof FormSuccessResponseSchema>;
export function checkResponseContract(value: unknown): value is Static<typeof FormResponseContractSchema>;
