/**
 * Subtree snapshots — the shared capture/restore engine behind the editor
 * clipboard (copy/cut/paste) and saved layouts (save-as-layout/insert).
 *
 * A snapshot contains nodes, style rules and their CSS condition dependencies:
 * the flat node map of one or more captured subtrees plus the authored CSS
 * needed to render them. Restoring a snapshot mints fresh node ids and
 * runs the class plan below, so both paste and layout insertion behave
 * identically — one engine, two front doors.
 *
 * Class restore rules (shared contract):
 * - Framework classes (`framework:*`) are matched by NAME against the target
 *   site's class registry; if no match exists, the classId is dropped.
 *   Framework classes are deterministically generated by the active document,
 *   so importing stale generated definitions would pollute it.
 * - Scoped (module-style) classes are always cloned with a fresh ID and the
 *   `scope.nodeId` remapped to the new node ID; scopes referencing nodes
 *   outside the captured subtree are dropped.
 * - All other (regular) classes are imported into the target site preserving
 *   their original ID. Same-ID classes already in the target are reused.
 */

import { nanoid } from 'nanoid'
import type { ConditionDef, CSSRuleGroup, NodeTree, PageNode, SiteDocument, StyleRule } from '@core/page-tree'
import { breakpointMediaQuery, buildSubtreeNodeIdMap, conditionId, pasteSubtree } from '@core/page-tree'
import { treeShakeStyleRules } from '@core/publisher'
import { Value } from '@core/utils/typeboxHelpers'
import type { InsertLocation } from '@site/store/insertLocation'
import { ruleOrderAfter } from './slices/styleRule/helpers'

/** Captured subtrees and their complete CSS dependencies. */
interface SubtreeSnapshot {
  /** Ordered root node ids inside `nodes`. */
  rootNodeIds: string[]
  /** Flat map of every node in every captured subtree. */
  nodes: Record<string, PageNode>
  /** Style rules referenced by any captured node. */
  classes: Record<string, StyleRule>
  conditions?: ConditionDef[]
}

/**
 * Collect the subtrees rooted at every id in `rootIds` into a single flat
 * nodes map. Skips ids not present in the tree (returning a non-null result as
 * long as at least one root resolved). Node and children arrays are copied so
 * the snapshot is detached from the live tree.
 */
export function collectSubtreeNodes(
  tree: NodeTree<PageNode>,
  rootIds: string[],
): { rootNodeIds: string[]; nodes: Record<string, PageNode> } | null {
  if (rootIds.length === 0) return null
  const nodes: Record<string, PageNode> = {}
  const validRoots: string[] = []
  for (const rootId of rootIds) {
    if (!tree.nodes[rootId]) continue
    validRoots.push(rootId)
    const stack = [rootId]
    while (stack.length > 0) {
      const id = stack.pop()!
      if (nodes[id]) continue
      const node = tree.nodes[id]
      if (!node) continue
      nodes[id] = Value.Clone(node)
      stack.push(...node.children)
    }
  }
  if (validRoots.length === 0) return null
  return { rootNodeIds: validRoots, nodes }
}

/**
 * Collect the authored rules used by captured nodes, including ambient rules,
 * grouping declarations, keyframes and registered properties. Conditions and
 * viewport queries travel with the snapshot so paste between installations preserves CSS
 * meaning even when the destination has different viewport definitions.
 */
export function collectSubtreeStyles(
  nodes: Record<string, PageNode>,
  site: Pick<SiteDocument, 'styleRules' | 'conditions' | 'breakpoints'>,
): { classes: Record<string, StyleRule>; conditions: ConditionDef[] } {
  const usedIds = new Set<string>()
  for (const node of Object.values(nodes)) {
    for (const classId of node.classIds) usedIds.add(classId)
  }
  const selected = treeShakeStyleRules(site.styleRules, usedIds)
  // Generated framework definitions are excluded from published authored CSS,
  // but their names are needed to match references in the destination site.
  for (const id of usedIds) if (site.styleRules[id]) selected[id] = site.styleRules[id]
  const classes: Record<string, StyleRule> = {}
  const contextIds = new Set<string>()
  for (const rule of Object.values(selected).sort((a, b) => a.order - b.order)) {
    if (rule.scope && !nodes[rule.scope.nodeId] && !usedIds.has(rule.id)) continue
    classes[rule.id] = Value.Clone(rule)
    for (const id of ruleContextIds(rule)) contextIds.add(id)
  }
  const conditions = [...contextIds].map((id): ConditionDef => {
    const condition = site.conditions?.find((entry) => entry.id === id)
    if (condition) return Value.Clone(condition)
    const viewport = site.breakpoints.find((entry) => entry.id === id)
    if (!viewport) throw new Error(`Cannot copy styles: CSS context "${id}" is missing`)
    return { id, label: viewport.label, condition: { kind: 'media', query: breakpointMediaQuery(viewport) } }
  })
  return { classes, conditions }
}

function ruleContextIds(rule: StyleRule): string[] {
  return [
    ...Object.keys(rule.contextStyles),
    ...Object.keys(rule.contextStylePriorities ?? {}),
    ...(rule.grouping ?? []).flatMap((group) => group.kind === 'context' ? [group.contextId] : []),
    ...(rule.atRule?.kind === 'group' && rule.atRule.group.kind === 'context' ? [rule.atRule.group.contextId] : []),
  ]
}

const FRAMEWORK_ID_PREFIX = 'framework:'

/**
 * Restore a snapshot into `tree` at `location`, materialising restored classes
 * into `site.styleRules`. Both `tree` and `site` are expected to be Mutative
 * drafts inside one store transaction, so the node paste and the class writes
 * land in a single undo step.
 *
 * Every root is placed consecutively at the resolved location in snapshot
 * order. Returns the new root node ids (snapshot order).
 *
 * Callers own the policy guards (e.g. the one-outlet-per-document invariant) —
 * this function only performs the mechanical restore.
 */
export function insertSnapshotSubtrees(
  tree: NodeTree<PageNode>,
  site: SiteDocument,
  snapshot: SubtreeSnapshot,
  location: InsertLocation,
): string[] {
  // Pre-compute new node IDs across ALL roots so scoped-class scope.nodeId
  // can be remapped before classes are written into the target site.
  // Each root's subtree gets its own id-remap; we union them into one map
  // so a class scoped to any restored node finds its remap.
  const nodeIdMap = new Map<string, string>()
  for (const rootId of snapshot.rootNodeIds) {
    const subtreeMap = buildSubtreeNodeIdMap(rootId, snapshot.nodes)
    for (const [oldId, newId] of subtreeMap) {
      if (!nodeIdMap.has(oldId)) nodeIdMap.set(oldId, newId)
    }
  }

  // Build the class plan. Each entry resolves to one of:
  //   - { kind: 'reuse', id }   — already present in target site
  //   - { kind: 'add', cls }    — write `cls` to site.styleRules (id may differ)
  //   - { kind: 'drop' }        — strip from restored classIds
  type ClassPlan =
    | { kind: 'reuse'; id: string }
    | { kind: 'add'; id: string; cls: StyleRule }
    | { kind: 'drop' }

  const now = Date.now()
  const targetClasses = site.styleRules
  const plans = new Map<string, ClassPlan>()
  const contextIds = new Map<string, string>()
  const conditions = [...(site.conditions ?? [])]
  for (const source of snapshot.conditions ?? []) {
    const signature = conditionId(source.condition)
    const condition = conditions.find((entry) => conditionId(entry.condition) === signature)
    const viewport = source.condition.kind === 'media'
      ? site.breakpoints.find((entry) => breakpointMediaQuery(entry) === source.condition.query)
      : undefined
    if (condition || viewport) {
      contextIds.set(source.id, (condition ?? viewport)!.id)
      continue
    }
    const id = conditions.some((entry) => entry.id === signature)
      || site.breakpoints.some((entry) => entry.id === signature) ? nanoid() : signature
    conditions.push({ ...Value.Clone(source), id })
    contextIds.set(source.id, id)
  }
  const groupIds = new Map<string, string>()
  const remapGroup = (group: CSSRuleGroup): CSSRuleGroup => {
    let id = groupIds.get(group.id)
    if (!id) { id = nanoid(); groupIds.set(group.id, id) }
    return group.kind === 'context'
      ? { ...group, id, contextId: contextIds.get(group.contextId) ?? group.contextId }
      : { ...group, id }
  }
  let nextOrder = Object.values(targetClasses).reduce((next, rule) => Math.max(next, rule.order + 1), 0)
  const copiedRule = (source: StyleRule): StyleRule => {
    const rule = Value.Clone(source)
    const existing = targetClasses[source.id]
    // A scoped copy whose source is still in this registry stays beside that
    // source, inside the same anonymous layer occurrence. An imported snapshot
    // gets a new namespace and appends its complete cohort instead.
    rule.order = existing ? ruleOrderAfter(targetClasses, existing) : nextOrder++
    rule.contextStyles = Object.fromEntries(Object.entries(rule.contextStyles).map(([id, bag]) => [contextIds.get(id) ?? id, bag]))
    if (rule.contextStylePriorities) rule.contextStylePriorities = Object.fromEntries(Object.entries(rule.contextStylePriorities).map(([id, bag]) => [contextIds.get(id) ?? id, bag]))
    const restoreGroup = (group: CSSRuleGroup): CSSRuleGroup => existing
      ? group.kind === 'context' ? { ...group, contextId: contextIds.get(group.contextId) ?? group.contextId } : group
      : remapGroup(group)
    if (rule.grouping) rule.grouping = rule.grouping.map(restoreGroup)
    if (rule.atRule?.kind === 'group') rule.atRule.group = restoreGroup(rule.atRule.group)
    for (const id of ruleContextIds(rule)) {
      if (!conditions.some((entry) => entry.id === id) && !site.breakpoints.some((entry) => entry.id === id)) {
        throw new Error(`Cannot restore styles: CSS context "${id}" is missing`)
      }
    }
    return rule
  }

  // Build a name → id index for framework classes in the active document
  // (used to match regenerated framework references that may have a
  // different id than the snapshot).
  const frameworkByName = new Map<string, string>()
  for (const [id, cls] of Object.entries(targetClasses)) {
    if (id.startsWith(FRAMEWORK_ID_PREFIX)) frameworkByName.set(cls.name, id)
  }

  for (const cls of Object.values(snapshot.classes).sort((a, b) => a.order - b.order)) {
    const classId = cls.id
    if (cls.scope?.type === 'node') {
      // Scoped class — always cloned with a fresh id, scope.nodeId remapped.
      const newScopeNodeId = nodeIdMap.get(cls.scope.nodeId)
      if (!newScopeNodeId) {
        plans.set(classId, { kind: 'drop' })
        continue
      }
      const newId = nanoid()
      plans.set(classId, {
        kind: 'add',
        id: newId,
        cls: {
          ...copiedRule(cls),
          id: newId,
          scope: { ...cls.scope, nodeId: newScopeNodeId },
          createdAt: now,
          updatedAt: now,
        },
      })
    } else if (classId.startsWith(FRAMEWORK_ID_PREFIX)) {
      // Framework class — reuse if id matches; else try by name; else drop.
      if (targetClasses[classId]) {
        plans.set(classId, { kind: 'reuse', id: classId })
      } else {
        const matchedId = frameworkByName.get(cls.name)
        plans.set(
          classId,
          matchedId
            ? { kind: 'reuse', id: matchedId }
            : { kind: 'drop' },
        )
      }
    } else {
      // Regular class — reuse if id is already in target, else import as-is.
      if (targetClasses[classId]) {
        plans.set(classId, { kind: 'reuse', id: classId })
      } else {
        plans.set(classId, {
          kind: 'add',
          id: classId,
          cls: copiedRule(cls),
        })
      }
    }
  }

  // classIdRemap: classes referenced by the subtree but not present in
  // snapshot.classes (e.g. payload was hand-edited) silently fall through —
  // reused if they exist in the target, dropped otherwise.
  const classIdRemap = (classId: string): string | null => {
    const plan = plans.get(classId)
    if (plan) {
      if (plan.kind === 'drop') return null
      return plan.id
    }
    return targetClasses[classId] ? classId : null
  }

  // 1. Materialise added classes into the target site.
  if (conditions.length !== (site.conditions?.length ?? 0)) site.conditions = conditions
  for (const plan of plans.values()) {
    if (plan.kind === 'add' && !site.styleRules[plan.id]) {
      site.styleRules[plan.id] = plan.cls
    }
  }

  // 2. Insert each root's subtree at the resolved location, preserving
  //    snapshot order. For "inside" inserts (target accepts children),
  //    every root is appended; for indexed inserts, each root increments
  //    the insertion index so siblings end up adjacent.
  const newRootIds: string[] = []
  let runningIndex = location.index
  for (const rootId of snapshot.rootNodeIds) {
    const newId = pasteSubtree(
      tree,
      { rootNodeId: rootId, nodes: snapshot.nodes },
      location.parentId,
      runningIndex,
      { nodeIdMap, classIdRemap },
    )
    newRootIds.push(newId)
    if (typeof runningIndex === 'number') runningIndex += 1
  }

  return newRootIds
}
