import { resolve } from 'node:path'
import { TypeCompiler } from '@sinclair/typebox/compiler'
import { PropertyConditionSchema } from '@core/module-engine-schema'
import {
  FormTransportSchema, FormControlBehaviorSchema, FormChallengeResponseSchema,
  FormJsonResponseSchema, TurnstileConfigurationSchema, TurnstileApiSchema,
  FormValidationResponseSchema, FormSuccessResponseSchema, FormResponseContractSchema,
} from '@core/forms-schema'

const root = resolve(import.meta.dir, '..')
const schemas = { checkCondition: PropertyConditionSchema, checkTransport: FormTransportSchema,
  checkControl: FormControlBehaviorSchema, checkChallenge: FormChallengeResponseSchema,
  checkJsonResponse: FormJsonResponseSchema, checkTurnstileConfiguration: TurnstileConfigurationSchema,
  checkTurnstileApi: TurnstileApiSchema, checkValidationResponse: FormValidationResponseSchema,
  checkSuccessResponse: FormSuccessResponseSchema, checkResponseContract: FormResponseContractSchema }
const names = ['PropertyConditionSchema','FormTransportSchema','FormControlBehaviorSchema','FormChallengeResponseSchema','FormJsonResponseSchema','TurnstileConfigurationSchema','TurnstileApiSchema','FormValidationResponseSchema','FormSuccessResponseSchema','FormResponseContractSchema']
const header = '/** TypeBox validators generated by bun run forms:sync; no runtime compiler. */\n'
export async function buildFormRuntimeArtifacts() {
  const validators = header + Object.entries(schemas).map(([name, schema]) => `export const ${name} = (() => {\n${TypeCompiler.Code(schema)}\n})();\n`).join('\n')
  const declarations = header + "import type { Static } from '@sinclair/typebox';\nimport type { PropertyConditionSchema } from '@core/module-engine-schema';\nimport type { " + names.slice(1).join(', ') + " } from '@core/forms-schema';\n" + Object.keys(schemas).map((name, index) => `export function ${name}(value: unknown): value is Static<typeof ${names[index]}>;\n`).join('')
  const built = await Bun.build({ entrypoints: [root + '/src/modules/base/forms/runtimeEntry.ts'], target: 'browser', format: 'iife', minify: true })
  if (!built.success) throw new AggregateError(built.logs, 'Native form runtime build failed')
  const script = await built.outputs[0].text()
  if (/\beval\s*\(|new Function\s*\(/.test(script)) throw new Error('Native form runtime must not need unsafe-eval')
  const output = root + '/src/modules/base/forms/formRuntimeJs.ts'
  const source = '/** Generated from runtimeEntry.ts by bun run forms:sync. */\nexport const FORM_RUNTIME_JS = ' + JSON.stringify(script) + '\n'
  return [{ path: root + '/src/modules/base/forms/runtimeValidators.js', content: validators }, { path: root + '/src/modules/base/forms/runtimeValidators.d.ts', content: declarations }, { path: output, content: source }]
}

if (import.meta.main) {
  for (const artifact of await buildFormRuntimeArtifacts()) {
    if (process.argv.includes('--check')) {
      if ((await Bun.file(artifact.path).text()).replace(/\r\n/g, '\n') !== artifact.content) throw new Error('Native form artifact is stale: ' + artifact.path + '; run bun run forms:sync')
    } else await Bun.write(artifact.path, artifact.content)
  }
}
